---
kind: pipeline
type: docker
name: default

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./node_modules

- name: website
  image: node:18
  commands:
  - mkdir -p $HOME/.ssh
  - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
  - echo "$GITHUB_PRIVATE_KEY" > "$HOME/.ssh/id_rsa"
  - chmod 0600 $HOME/.ssh/id_rsa
  - yarn install --frozen-lockfile
  - npm run deploy
  environment:
    USE_SSH: true
    GIT_USER: $DRONE_COMMIT_AUTHOR
    GITHUB_PRIVATE_KEY:
      from_secret: "git_deploy_private_key"
    ALGOLIA_APP_ID:
      from_secret: "algolia_app_id"
    ALGOLIA_API_KEY:
      from_secret: "algolia_api_key"
    ALGOLIA_INDEX_NAME:
      from_secret: "algolia_index_name"
    UMAMI_ID:
      from_secret: "umami_id"
    UMAMI_URL:
      from_secret: "umami_url"
  when:
    event:
      include:
      - push
      - pull_request

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./node_modules

- name: notify
  image: plugins/webhook
  settings:
    urls:
      from_secret: NODE_RED_WEBHOOK
  when:
    status:
    - success
    - failure

volumes:
  - name: cache
    host: 
      path: /var/lib/dokku/data/storage/hfr-drone-runner/cache

trigger:
  branch:
  - main
